#!/bin/bash

SCRIPT_DIRECTORY=$(dirname "$0")
#source "${SCRIPT_DIRECTORY}/extensions/http.conf"

# Probe - Configuration

PROBE=http     # Name of the probe
COLOR=green    # By default, everything is OK
MSG_LONG=""
MSG_SHORT=""

# Probe - Implementation

# Use input redirection instead of a pipe
while read -r url; do
    RESULT=$(curl -s -I "$url" | grep HTTP)

    if [ "$RESULT" != "200" ]; then
        COLOR=red
        MSG_SHORT="$RESULT"
    fi
done <<EOF
$(cat "${SCRIPT_DIRECTORY}/http.hosts")
EOF

# Probe - Result

#printf '%s %s\n' "$PROBE $COLOR $(date)" "$MSG_SHORT\n$MSG_LONG"
printf '%s %s\n' "$PROBE $COLOR $(date)" "$MSG_SHORT"

exit 0

